# Generated by Django 3.1.1 on 2020-10-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JMIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_count', models.IntegerField(blank=True, null=True, verbose_name='Reference Count')),
                ('publisher', models.CharField(default='', max_length=200, verbose_name='publisher')),
                ('issue', models.IntegerField(blank=True, null=True, verbose_name='issue')),
                ('short_container_title', models.CharField(default='', max_length=200, verbose_name='Short Container title')),
                ('DOI', models.CharField(default='', max_length=150, verbose_name='DOI')),
                ('article_type', models.CharField(default='', max_length=100, verbose_name='Type')),
                ('page', models.CharField(default='', max_length=150, verbose_name='Page')),
                ('source', models.CharField(default='', max_length=100, verbose_name='Source')),
                ('title', models.CharField(default='', max_length=500, verbose_name='Title')),
                ('prefix', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Prefix')),
                ('volumne', models.IntegerField(blank=True, null=True, verbose_name='volume')),
                ('member', models.IntegerField(blank=True, null=True, verbose_name='member')),
                ('container_title', models.CharField(default='', max_length=300, verbose_name='Container Title')),
                ('language', models.CharField(default='', max_length=5, verbose_name='language')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Score')),
                ('issn', models.CharField(default='', max_length=50, verbose_name='issn')),
                ('url', models.CharField(default='', max_length=200, verbose_name='url')),
            ],
        ),
    ]
