# Generated by Django 3.1.1 on 2020-10-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jmir',
            old_name='volumne',
            new_name='volume',
        ),
    ]
