# Generated by Django 3.1.1 on 2020-10-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmir', '0002_auto_20201010_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jmir',
            old_name='issue',
            new_name='issuex',
        ),
    ]
